### ISSUE TITLE
_spectrom_sync_details meta is not updated after pushing

### ISSUE THREAD

**Issue by Patrick64** [ServerPress/wpsitesync#12]
Currently the sync info is updated every 3 minutes (in classes/admin.php `get_content_details()` function), however it is not updated after syncing. It would be better if after a sync it updates this info rather than needing to wait 3 minutes.

**Comment by Patrick64** [comment]
I'm happy to give this a go and make a pull request if you can give me pointers on where I should add the code @davejesch @erinmarinas

**Comment by davejesch** [comment]
Hi @Patrick64  Thanks for reporting this. There's quite a bit involved in fixing this. We'd need to change the results of the Push API call to include these details in the response. We've entered this as an enhancement in our private repo (where we do all of our bug tracking) and we'll let you know when this has been addressed.
