### ISSUE TITLE
1.6.1 Release in repo

### ISSUE THREAD

**Issue by Patrick64** [ServerPress/wpsitesync#14]
I think this repo is out of date. Is there any possibly of updating this repo with the latest release?

**Comment by davejesch** [comment]
Hi @Patrick64  - Yes, it is out of date. We're working on a new release which should be available soon. We'll be sure to update the releases here. In the mean time, to get the current code you can download it from the WP repository: https://wordpress.org/plugins/wpsitesynccontent/
