### ISSUE TITLE
Invalid URL warning on Target site

### ISSUE THREAD

**Issue by vegasgeek** [ServerPress/wpsitesync#4]
## Description

While setting up WPSiteSync, when I click the Save Changes button, I receive the error "Invalid URL." error.

## Steps to recreate

1. On Local site, install/activate WPSiteSync
2. On Live site, install/activate WPSiteSync
3. On Local site, Update General settings that include target/username/password
4. On Live site, Update General settings but leave target/username/password blank

<img width="1276" alt="Screen Shot 2019-03-09 at 8 38 00 AM" src="https://user-images.githubusercontent.com/367562/54074379-ad0d8880-4246-11e9-97ae-10b6d6f3f7d1.png">

**Comment by davejesch** [comment]
See: https://github.com/ServerPress/sync/issues/220

**Comment by vegasgeek** [comment]
@davejesch that repo bust be private as I'm getting a 404 error.

**Comment by erinmarinas** [comment]
Fixed
davejesch said: "added check for empty target url on settings save"
