### ISSUE TITLE
WPSS box disappears when reopening Gutenberg sidebar

### ISSUE THREAD

**Issue by vegasgeek** [ServerPress/wpsitesync#5]
## Description

While editing a post on my local install, after hitting save, I closed the sidebar (on accident), and when I reopened it, the WP Site Sync sidebar block was missing. The only way I was able to get it back was to exit the post by going to All Posts and then clicking Edit post to reopen it.

## Steps to recreate
(all of this is on local machine)

1. Create a new blog post
2. Publish the post
3. At this point, the WPSS box isn't being displayed (an issue for another ticket), exit the post by going back to All Posts.
4. Click to edit post (the WPSS sidebar box is now showing)
5. Click the gear to hide the Gutenberg sidebar
6. Click the gear to display the Gutenberg sidebar again (the WPSS sidebar box is missing)

Here's a video of me doing this exact process.
http://vegasgeek.net/2019/f9VR8maQfanfrticfe84.gif

**Comment by davejesch** [comment]
See: https://github.com/ServerPress/sync/issues/221

**Comment by erinmarinas** [comment]
Issue has been fixed and will be included in WPSiteSync's next update
